services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app/backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/backend
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./fastapi_app/frontend/src:/app/src
      - ./fastapi_app/frontend/public:/app/public
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend-node-modules: 